#!/usr/bin/env python
#Author Shabashkin.O
#этот скрипт правит Makefile сгенерированный STM32CubeMx удаляя из него повторяющиеся строки между "# C sources" и "# ASM sources"
#тем самым избавляя нас от ручного поиска и удаления повторяющихся строк в указанном диапазоне, проект может быть большой, строк много, выискивать лень.
#запускать в той же папке где лежит Makefile
#this script rules the Makefile generated by STM32CubeMx by removing from it the duplicate lines between "# C sources" and "# ASM sources"
#run in the same folder as the Makefile
import os
lists_0=[]#all string in Makefile
lists_1=[]
lists_2=[]
lists_3=[]
dates=[]#string after deleting repetitions in lists_2
with open ('Makefile',encoding='utf-8') as inf :
    for line in inf:
            line=line.strip()
            lists_0.append(line)
lists_1 = lists_0[:lists_0.index("# C sources",0,-1)]#string before "# C sources"
lists_2 = lists_0[lists_0.index("# C sources",0,-1):lists_0.index("# ASM sources",0,-1)]#string between "# C sources" and "# ASM sources"
lists_3 = lists_0[lists_0.index("# ASM sources",0,-1):]#string after "# ASM sources"
for i in lists_2 :
    if i not in dates :
        dates.append(i)
with open ('Makefile', 'w') as outp :
    for line in lists_1:
        outp.write(line + '\n')
    for line in dates :
        outp.write(line + '\n')
    for line in lists_3 :
        outp.write(line + '\n')
print("done")